name: PR Review Automation

on:
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  gpt-review:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install gpt-review CLI
        run: |
          python -m pip install --upgrade pip
          pip install gpt-review

      - name: Review Pull Request with GPT
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GIT_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          PULL_REQUEST_NUMBER=$(jq --raw-output '.number' < $GITHUB_EVENT_PATH)
          REPOSITORY_NAME=${{ github.repository }}
          gpt github review \
            --access-token $GITHUB_ACCESS_TOKEN \
            --pull-request $PULL_REQUEST_NUMBER \
            --repository $REPOSITORY_NAME
